/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.dijalozi;

import domen.Grad;
import domen.Ponuda;
import domen.StavkaPonude;
import forme.FrmKreiranjePonude;
import forme.FrmKreiranjeRezervacije;
import forme.paneli.FrmMode;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kotroler.Kontroler;
import model.ModelTabelePonude;
import model.ModelTabeleStavkePonude;

/**
 *
 * @author Jovana Mitrovic
 */
public class FrmPretragaPonuda extends javax.swing.JDialog {

    FrmMode mode;

    /**
     * Creates new form FrmPretragaPonuda
     */
    public FrmPretragaPonuda(java.awt.Frame parent, boolean modal, FrmMode mode) {
        super(parent, modal);
        this.mode = mode;
        initComponents();
        pnlStavkePonude.setVisible(false);
        btnIzaberiPonudu.setVisible(false);
        popuniGradove();
        popuniTabelu();
        tblStavkePonude.setColumnSelectionAllowed(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrikaziStavke = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnPretrazi = new javax.swing.JButton();
        dpcDatumOd = new datechooser.beans.DateChooserCombo();
        dpcDatumDo = new datechooser.beans.DateChooserCombo();
        cmbGrad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPonude = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlStavkePonude = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkePonude = new javax.swing.JTable();
        btnIzaberiPonudu = new javax.swing.JButton();
        btnUnesiNovuPonudu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPrikaziStavke.setText("Prikazi stavke");
        btnPrikaziStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkeActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga ponuda"));

        btnPretrazi.setText("Pretrazi ponude");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblPonude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPonude);

        jLabel1.setText("Datum od:");

        jLabel2.setText("Datum do:");

        jLabel3.setText("Grad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpcDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpcDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretrazi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpcDatumDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpcDatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPretrazi))
                    .addComponent(cmbGrad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlStavkePonude.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke ponude"));

        tblStavkePonude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavkePonude);

        javax.swing.GroupLayout pnlStavkePonudeLayout = new javax.swing.GroupLayout(pnlStavkePonude);
        pnlStavkePonude.setLayout(pnlStavkePonudeLayout);
        pnlStavkePonudeLayout.setHorizontalGroup(
            pnlStavkePonudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkePonudeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlStavkePonudeLayout.setVerticalGroup(
            pnlStavkePonudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkePonudeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnIzaberiPonudu.setText("Izaberi ponudu");
        btnIzaberiPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiPonuduActionPerformed(evt);
            }
        });

        btnUnesiNovuPonudu.setText("Unesi novu ponudu");
        btnUnesiNovuPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNovuPonuduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStavkePonude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnesiNovuPonudu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrikaziStavke))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzaberiPonudu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziStavke)
                    .addComponent(btnUnesiNovuPonudu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStavkePonude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzaberiPonudu)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        Date datumOd = dpcDatumOd.getSelectedDate().getTime();
        Date datumDo = dpcDatumDo.getSelectedDate().getTime();
        Grad g = (Grad) cmbGrad.getSelectedItem();
        Ponuda p = new Ponuda();
        p.setDatumOd(datumOd);
        p.setDatumDo(datumDo);
        if (!g.getNaziv().toLowerCase().equals("svi gradovi")) {
            p.setGrad(g);
        }

        try {
            List<Ponuda> ponude = Kontroler.getInstanca().pretraziPonude(p);
            if(ponude.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ne postoje rezultati pretrage");
                tblStavkePonude.setModel(new ModelTabeleStavkePonude(new ArrayList<>()));
            }
            tblPonude.setModel(new ModelTabelePonude(ponude));
            pnlStavkePonude.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaPonuda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPrikaziStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkeActionPerformed
        int red = tblPonude.getSelectedRow();
        if (red != -1) {
            ModelTabelePonude model = (ModelTabelePonude) tblPonude.getModel();
            Ponuda p = model.vratiPonudu(red);
            tblStavkePonude.setModel(new ModelTabeleStavkePonude(p.getStavke()));
            pnlStavkePonude.setVisible(true);
            if (mode == FrmMode.PRIKAZ) {
                btnIzaberiPonudu.setVisible(true);
            }
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Selektujte red", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziStavkeActionPerformed

    private void btnIzaberiPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiPonuduActionPerformed
        int red = tblStavkePonude.getSelectedRow();
        if (red != -1) {
            ModelTabeleStavkePonude model = (ModelTabeleStavkePonude) tblStavkePonude.getModel();
            StavkaPonude sp = model.vratiStavkuPonude(red);
            FrmKreiranjeRezervacije frm = (FrmKreiranjeRezervacije) getParent();
            frm.ubaciPonudu(sp);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selektujte red", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzaberiPonuduActionPerformed

    private void btnUnesiNovuPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNovuPonuduActionPerformed
        FrmKreiranjePonude frm = new FrmKreiranjePonude();
        frm.setLocationRelativeTo(this);
        frm.pack();
        frm.setVisible(true);
        frm.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnUnesiNovuPonuduActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiPonudu;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziStavke;
    private javax.swing.JButton btnUnesiNovuPonudu;
    private javax.swing.JComboBox<Grad> cmbGrad;
    private datechooser.beans.DateChooserCombo dpcDatumDo;
    private datechooser.beans.DateChooserCombo dpcDatumOd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlStavkePonude;
    private javax.swing.JTable tblPonude;
    private javax.swing.JTable tblStavkePonude;
    // End of variables declaration//GEN-END:variables

    private void popuniGradove() {
        try {
            Grad g = new Grad(0, "Svi gradovi", null);
            List<Grad> list = new ArrayList<>();
            list.add(g);
            list.addAll(Kontroler.getInstanca().vratiGradove());
            cmbGrad.setModel(new DefaultComboBoxModel(list.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaPonuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniTabelu() {
        tblPonude.setModel(new ModelTabelePonude(new ArrayList<>()));
    }

}
