/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.dijalozi;

import domen.Klijent;
import forme.FrmKreiranjeRezervacije;
import forme.paneli.FrmMode;
import forme.paneli.PnlKlijent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kotroler.Kontroler;
import model.ModelTabeleKlijenti;
import sesija.Sesija;

/**
 *
 * @author Jovana Mitrovic
 */
public class FrmPretragaKlijenata extends javax.swing.JDialog {

    FrmMode mode;

    /**
     * Creates new form FrmPretragaKlijenata
     */
    public FrmPretragaKlijenata(java.awt.Frame parent, boolean modal, FrmMode mode) {
        super(parent, modal);
        this.mode = mode;
        initComponents();
        srediFormu();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIzaberiKlijenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnIzmeniKlijenta = new javax.swing.JButton();
        btnUnesiNovogKlijenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnIzaberiKlijenta.setText("Izaberi klijenta");
        btnIzaberiKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiKlijentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime:");

        txtIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeKeyReleased(evt);
            }
        });

        jLabel2.setText("Prezime:");

        txtPrezime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrezimeKeyReleased(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        btnIzmeniKlijenta.setText("Izmeni klijenta");
        btnIzmeniKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKlijentaActionPerformed(evt);
            }
        });

        btnUnesiNovogKlijenta.setText("Unesi novog klijenta");
        btnUnesiNovogKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNovogKlijentaActionPerformed(evt);
            }
        });

        jButton1.setText("Prikazi sve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnesiNovogKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniKlijenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzaberiKlijenta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzaberiKlijenta)
                            .addComponent(btnUnesiNovogKlijenta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnIzmeniKlijenta)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiKlijentaActionPerformed
        int red = tblKlijenti.getSelectedRow();
        if (red != -1) {
            ModelTabeleKlijenti model = (ModelTabeleKlijenti) tblKlijenti.getModel();
            Klijent k = model.vratiKlijenta(red);
            FrmKreiranjeRezervacije frm = (FrmKreiranjeRezervacije) getParent();
            frm.ubaciKlijenta(k);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selektujte red", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzaberiKlijentaActionPerformed

    private void btnIzmeniKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKlijentaActionPerformed
        int red = tblKlijenti.getSelectedRow();
        if (red != -1) {
            ModelTabeleKlijenti model = (ModelTabeleKlijenti) tblKlijenti.getModel();
            Klijent k = model.vratiKlijenta(red);
            Sesija.getInstanca().getMapa().clear();
            Sesija.getInstanca().getMapa().put("Klijent", k);
            JDialog dialog = new JDialog(this, true);
            PnlKlijent pnl = new PnlKlijent(FrmMode.IZMENA);
            dialog.setContentPane(pnl);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selektujte red", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniKlijentaActionPerformed

    private void btnUnesiNovogKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNovogKlijentaActionPerformed
        JDialog dialog = new JDialog(this, true);
        dialog.setContentPane(new PnlKlijent(FrmMode.UNOS));
        dialog.setLocationRelativeTo(this);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnUnesiNovogKlijentaActionPerformed

    private void txtImeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeKeyReleased
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        Klijent k = new Klijent();
        if (!ime.isEmpty()) {
            k.setIme(ime);
        }
        if (!prezime.isEmpty()) {
            k.setPrezime(prezime);
        }
        try {
            List<Klijent> list = Kontroler.getInstanca().pretraziKlijente(k);
            tblKlijenti.setModel(new ModelTabeleKlijenti(list));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaKlijenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtImeKeyReleased

    private void txtPrezimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeKeyReleased
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        Klijent k = new Klijent();
        if (!ime.isEmpty()) {
            k.setIme(ime);
        }
        if (!prezime.isEmpty()) {
            k.setPrezime(prezime);
        }
        List<Klijent> list;
        try {
            list = Kontroler.getInstanca().pretraziKlijente(k);
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ne postoje rezultati pretrage");
                return;
            }
            tblKlijenti.setModel(new ModelTabeleKlijenti(list));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaKlijenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPrezimeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Klijent k = new Klijent();
        try {
            List<Klijent> list = Kontroler.getInstanca().pretraziKlijente(k);
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ne postoje rezultati pretrage");
                return;
            }
            tblKlijenti.setModel(new ModelTabeleKlijenti(list));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaKlijenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiKlijenta;
    private javax.swing.JButton btnIzmeniKlijenta;
    private javax.swing.JButton btnUnesiNovogKlijenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        tblKlijenti.setModel(new ModelTabeleKlijenti(new ArrayList<>()));
    }

    private void srediFormu() {
        switch (mode) {
            case PRETRAGA:
                btnIzmeniKlijenta.setVisible(false);
                break;
            case IZMENA:
                btnIzaberiKlijenta.setVisible(false);
                btnUnesiNovogKlijenta.setVisible(false);
                break;
        }
    }
}
