/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.dijalozi;

import domen.StavkaPonude;
import domen.TipSobe;
import forme.FrmKreiranjePonude;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kotroler.Kontroler;

/**
 *
 * @author Jovana Mitrovic
 */
public class FrmUnosStavkePonude extends javax.swing.JDialog {

    /**
     * Creates new form FrmUnosStavkePonude
     */
    public FrmUnosStavkePonude(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniTipoveSoba();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKapacitet = new javax.swing.JTextField();
        btnUnesiStavkuPonude = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbTipSobe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Kapacitet:");

        btnUnesiStavkuPonude.setText("Unesi stavku ponude");
        btnUnesiStavkuPonude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiStavkuPonudeActionPerformed(evt);
            }
        });

        jLabel1.setText("Tip sobe:");

        jLabel2.setText("Cena:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTipSobe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCena)
                            .addComponent(txtKapacitet)
                            .addComponent(btnUnesiStavkuPonude, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUnesiStavkuPonude)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiStavkuPonudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiStavkuPonudeActionPerformed
        TipSobe ts = (TipSobe) cmbTipSobe.getSelectedItem();
        BigDecimal cena = new BigDecimal(txtCena.getText());
        int kapacitet = Integer.parseInt(txtKapacitet.getText());
        
        if(cena.compareTo(new BigDecimal(0))>0 && kapacitet>0) {
        StavkaPonude sp = new StavkaPonude(0, cena, kapacitet, ts);
        FrmKreiranjePonude frm = (FrmKreiranjePonude) getParent();
        frm.dodajStavkuPonude(sp);
        dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cena i kapacitet moraju biti veci od 0!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUnesiStavkuPonudeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesiStavkuPonude;
    private javax.swing.JComboBox<TipSobe> cmbTipSobe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtKapacitet;
    // End of variables declaration//GEN-END:variables

    private void popuniTipoveSoba() {
        try {
            List<TipSobe> list = Kontroler.getInstanca().vratiTipoveSoba();
            cmbTipSobe.setModel(new DefaultComboBoxModel(list.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmUnosStavkePonude.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
