/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.dijalozi.FrmPretragaKlijenata;
import forme.dijalozi.FrmPretragaPonuda;
import forme.paneli.FrmMode;
import forme.paneli.PnlKlijent;
import forme.paneli.PnlUnosHotela;
import java.awt.Dialog;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kotroler.Kontroler;
import sesija.Sesija;

/**
 *
 * @author Jovana Mitrovic
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        lblUlogovaniKorisnik.setText(Sesija.getInstanca().getKorisnik().getIme() + " " + Sesija.getInstanca().getKorisnik().getPrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUlogovaniKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKlijent = new javax.swing.JMenu();
        jmiUnosKlijenta = new javax.swing.JMenuItem();
        jmiIzmeniKlijenta = new javax.swing.JMenuItem();
        menuHotel = new javax.swing.JMenu();
        jmiUnosHotela = new javax.swing.JMenuItem();
        menuPonuda = new javax.swing.JMenu();
        jmiKreiranjePonude = new javax.swing.JMenuItem();
        jmiPretragaPonuda = new javax.swing.JMenuItem();
        menuRezervacija = new javax.swing.JMenu();
        jmiKreiranjeRezervacije = new javax.swing.JMenuItem();
        jmiPretragaRezervacija = new javax.swing.JMenuItem();
        menuOdjava = new javax.swing.JMenu();
        jmiOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ulogovani korisnik"));

        lblUlogovaniKorisnik.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblUlogovaniKorisnik)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUlogovaniKorisnik)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        menuKlijent.setText("Klijent");

        jmiUnosKlijenta.setText("Unos");
        jmiUnosKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKlijentaActionPerformed(evt);
            }
        });
        menuKlijent.add(jmiUnosKlijenta);

        jmiIzmeniKlijenta.setText("Pretraga / Izmena");
        jmiIzmeniKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmeniKlijentaActionPerformed(evt);
            }
        });
        menuKlijent.add(jmiIzmeniKlijenta);

        jMenuBar1.add(menuKlijent);

        menuHotel.setText("Hotel");

        jmiUnosHotela.setText("Unos");
        jmiUnosHotela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosHotelaActionPerformed(evt);
            }
        });
        menuHotel.add(jmiUnosHotela);

        jMenuBar1.add(menuHotel);

        menuPonuda.setText("Ponuda");

        jmiKreiranjePonude.setText("Kreiranje");
        jmiKreiranjePonude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjePonudeActionPerformed(evt);
            }
        });
        menuPonuda.add(jmiKreiranjePonude);

        jmiPretragaPonuda.setText("Pretraga");
        jmiPretragaPonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaPonudaActionPerformed(evt);
            }
        });
        menuPonuda.add(jmiPretragaPonuda);

        jMenuBar1.add(menuPonuda);

        menuRezervacija.setText("Rezervacija");

        jmiKreiranjeRezervacije.setText("Kreiranje");
        jmiKreiranjeRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeRezervacijeActionPerformed(evt);
            }
        });
        menuRezervacija.add(jmiKreiranjeRezervacije);

        jmiPretragaRezervacija.setText("Pretraga / Otkazivanje");
        jmiPretragaRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaRezervacijaActionPerformed(evt);
            }
        });
        menuRezervacija.add(jmiPretragaRezervacija);

        jMenuBar1.add(menuRezervacija);

        menuOdjava.setText("Odjava sa sistema");

        jmiOdjaviSe.setText("Odjavi se");
        jmiOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdjaviSeActionPerformed(evt);
            }
        });
        menuOdjava.add(jmiOdjaviSe);

        jMenuBar1.add(menuOdjava);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKlijentaActionPerformed
        JDialog dialog = new JDialog(this, false);
        dialog.setContentPane(new PnlKlijent(FrmMode.UNOS));
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiUnosKlijentaActionPerformed

    private void jmiUnosHotelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosHotelaActionPerformed
        JDialog dialog = new JDialog(this, false);
        dialog.setContentPane(new PnlUnosHotela());
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiUnosHotelaActionPerformed

    private void jmiKreiranjePonudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjePonudeActionPerformed
        FrmKreiranjePonude frm = new FrmKreiranjePonude();
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_jmiKreiranjePonudeActionPerformed

    private void jmiPretragaPonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaPonudaActionPerformed
        FrmPretragaPonuda frm = new FrmPretragaPonuda(this, true, FrmMode.PRETRAGA);
        frm.pack();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiPretragaPonudaActionPerformed

    private void jmiKreiranjeRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeRezervacijeActionPerformed
        FrmKreiranjeRezervacije frm = new FrmKreiranjeRezervacije(FrmMode.UNOS);
        frm.pack();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiKreiranjeRezervacijeActionPerformed

    private void jmiPretragaRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaRezervacijaActionPerformed
        FrmPretragaRezervacija frm = new FrmPretragaRezervacija();
        frm.pack();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiPretragaRezervacijaActionPerformed

    private void jmiIzmeniKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmeniKlijentaActionPerformed
        FrmPretragaKlijenata dialog = new FrmPretragaKlijenata(this,true,FrmMode.IZMENA);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiIzmeniKlijentaActionPerformed

    private void jmiOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdjaviSeActionPerformed
        try {
            Kontroler.getInstanca().odjaviSe();
            JOptionPane.showMessageDialog(this, "Uspesno ste se odjavili!");
            dispose();
            FrmLogIn frm = new FrmLogIn();
            frm.setLocationRelativeTo(null);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiOdjaviSeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Kontroler.getInstanca().odjaviSe();
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmiIzmeniKlijenta;
    private javax.swing.JMenuItem jmiKreiranjePonude;
    private javax.swing.JMenuItem jmiKreiranjeRezervacije;
    private javax.swing.JMenuItem jmiOdjaviSe;
    private javax.swing.JMenuItem jmiPretragaPonuda;
    private javax.swing.JMenuItem jmiPretragaRezervacija;
    private javax.swing.JMenuItem jmiUnosHotela;
    private javax.swing.JMenuItem jmiUnosKlijenta;
    private javax.swing.JLabel lblUlogovaniKorisnik;
    private javax.swing.JMenu menuHotel;
    private javax.swing.JMenu menuKlijent;
    private javax.swing.JMenu menuOdjava;
    private javax.swing.JMenu menuPonuda;
    private javax.swing.JMenu menuRezervacija;
    // End of variables declaration//GEN-END:variables
}
