/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Drzava;
import domen.Grad;
import domen.Hotel;
import domen.Ponuda;
import domen.StavkaPonude;
import forme.dijalozi.FrmUnosStavkePonude;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kotroler.Kontroler;
import model.ModelTabeleStavkePonude;

/**
 *
 * @author Jovana Mitrovic
 */
public class FrmKreiranjePonude extends javax.swing.JFrame {

    /**
     * Creates new form FrmKreiranjePonude
     */
    public FrmKreiranjePonude() {
        initComponents();
        popuniTabelu();
        popuniDrzave();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbDrzava = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbGrad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dpcDatumOd = new datechooser.beans.DateChooserCombo();
        dpcDatumDo = new datechooser.beans.DateChooserCombo();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnDodaj1 = new javax.swing.JButton();
        btnObrisi1 = new javax.swing.JButton();
        btnSacuvaj1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbHotel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kreiranje ponude"));

        jLabel5.setText("Drzava:");

        cmbDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDrzavaActionPerformed(evt);
            }
        });

        jLabel6.setText("Grad:");

        cmbGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradActionPerformed(evt);
            }
        });

        jLabel7.setText("Datum od: ");

        jLabel8.setText("Datum do:");

        dpcDatumOd.setLocale(new java.util.Locale("sr", "", ""));

        dpcDatumDo.setLocale(new java.util.Locale("sr", "", ""));
        dpcDatumDo.setMinDate(dpcDatumOd.getSelectedDate());

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnDodaj1.setText("Dodaj stavku");
        btnDodaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodaj1ActionPerformed(evt);
            }
        });

        btnObrisi1.setText("Obrisi stavku");
        btnObrisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisi1ActionPerformed(evt);
            }
        });

        btnSacuvaj1.setText("Sacuvaj ponudu");
        btnSacuvaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvaj1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Hotel:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(99, 99, 99)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dpcDatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                            .addComponent(dpcDatumDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbHotel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSacuvaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDodaj1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisi1)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpcDatumOd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(dpcDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj1)
                    .addComponent(btnObrisi1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrzavaActionPerformed
        Drzava d = (Drzava) cmbDrzava.getSelectedItem();
        Grad g = new Grad();
        g.setDrzava(d);
        try {
            List<Grad> list = Kontroler.getInstanca().vratiGradoveZaDrzavu(g);
            cmbGrad.setModel(new DefaultComboBoxModel(list.toArray()));
            cmbHotel.removeAllItems();
        } catch (Exception ex) {
            Logger.getLogger(FrmKreiranjePonude.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbDrzavaActionPerformed

    private void cmbGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradActionPerformed
        Grad g = (Grad) cmbGrad.getSelectedItem();
        Hotel h = new Hotel();
        h.setGrad(g);
        try {
            List<Hotel> list = Kontroler.getInstanca().vratiHoteleZaGrad(h);
            cmbHotel.setModel(new DefaultComboBoxModel(list.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmKreiranjePonude.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbGradActionPerformed

    private void btnDodaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodaj1ActionPerformed
//        ModelTabeleStavkePonude model = (ModelTabeleStavkePonude) tblStavke.getModel();
//        model.dodajStavku(new StavkaPonude());

        FrmUnosStavkePonude frm = new FrmUnosStavkePonude(this, true);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);

    }//GEN-LAST:event_btnDodaj1ActionPerformed

    private void btnObrisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisi1ActionPerformed
        int red = tblStavke.getSelectedRow();
        if (red != -1) {
            ModelTabeleStavkePonude model = (ModelTabeleStavkePonude) tblStavke.getModel();
            model.obrisiStavku(red);
        } else {
            JOptionPane.showMessageDialog(this, "Selektujte red!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisi1ActionPerformed

    private void btnSacuvaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvaj1ActionPerformed
        Drzava d = (Drzava) cmbDrzava.getSelectedItem();
        Grad g = (Grad) cmbGrad.getSelectedItem();
        Hotel h = (Hotel) cmbHotel.getSelectedItem();
        Date datumOd = dpcDatumOd.getSelectedDate().getTime();
        Date datumDo = dpcDatumOd.getSelectedDate().getTime();
        ModelTabeleStavkePonude model = (ModelTabeleStavkePonude) tblStavke.getModel();
        List<StavkaPonude> stavke = model.vratiStavke();
        Ponuda p = new Ponuda(0, datumOd, datumDo, h, g, stavke);
        try {
            if (validacija()) {
                Kontroler.getInstanca().kreirajPonudu(p);
                JOptionPane.showMessageDialog(this, "Uspesno sacuvana ponuda!");
                isprazniPoljaForme();
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmKreiranjePonude.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvaj1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj1;
    private javax.swing.JButton btnObrisi1;
    private javax.swing.JButton btnSacuvaj1;
    private javax.swing.JComboBox<Drzava> cmbDrzava;
    private javax.swing.JComboBox<Grad> cmbGrad;
    private javax.swing.JComboBox<Grad> cmbHotel;
    private datechooser.beans.DateChooserCombo dpcDatumDo;
    private datechooser.beans.DateChooserCombo dpcDatumOd;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStavke;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {

        tblStavke.setModel(new ModelTabeleStavkePonude(new ArrayList<>()));

//        try {
//            List<TipSobe> list = Kontroler.getInstanca().vratiTipoveSoba();
//            JComboBox cmb = new JComboBox(list.toArray());
//            TableColumn tc = tblStavke.getColumnModel().getColumn(1);
//            tc.setCellEditor(new DefaultCellEditor(cmb));
//        } catch (Exception ex) {
//            Logger.getLogger(FrmKreiranjePonude.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void popuniDrzave() {
        List<Drzava> list;
        try {
            list = Kontroler.getInstanca().vratiDrzave();
            cmbDrzava.setModel(new DefaultComboBoxModel(list.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmKreiranjePonude.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void dodajStavkuPonude(StavkaPonude sp) {
        ModelTabeleStavkePonude model = (ModelTabeleStavkePonude) tblStavke.getModel();
        model.dodajStavku(sp);
    }

    private void isprazniPoljaForme() {
        cmbDrzava.setSelectedIndex(0);
        dpcDatumOd.setSelectedDate(Calendar.getInstance());
        dpcDatumDo.setSelectedDate(Calendar.getInstance());
        tblStavke.setModel(new ModelTabeleStavkePonude(new ArrayList<>()));
    }

    private boolean validacija() {
        Drzava d = (Drzava) cmbDrzava.getSelectedItem();
        Grad g = (Grad) cmbGrad.getSelectedItem();
        Hotel h = (Hotel) cmbHotel.getSelectedItem();
        Date datumOd = dpcDatumOd.getSelectedDate().getTime();
        Date datumDo = dpcDatumOd.getSelectedDate().getTime();
        ModelTabeleStavkePonude model = (ModelTabeleStavkePonude) tblStavke.getModel();
        List<StavkaPonude> stavke = model.vratiStavke();

        if (d == null || g == null || h == null) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna!", "Greska", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (stavke.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ponuda mora sadrzati barem jednu stavku!", "Greska", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }
}
