/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.dijalozi.FrmPretragaPonuda;
import domen.Klijent;
import domen.Rezervacija;
import domen.StavkaPonude;
import forme.dijalozi.FrmPretragaKlijenata;
import forme.paneli.FrmMode;
import forme.paneli.PnlKlijent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import kotroler.Kontroler;
import sesija.Sesija;

/**
 *
 * @author Jovana Mitrovic
 */
public class FrmKreiranjeRezervacije extends javax.swing.JFrame {
    
    PnlKlijent pnlKlijent;
    Klijent k;
    StavkaPonude sp;
    FrmMode mode;

    /**
     * Creates new form FrmKreiranjeRezervacije
     */
    public FrmKreiranjeRezervacije(FrmMode mode) {
        initComponents();
        this.mode = mode;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKlijenta = new javax.swing.JPanel();
        btnIzaberiPonudu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDrzava = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGrad = new javax.swing.JTextField();
        txtDatumOd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDatumDo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHotel = new javax.swing.JTextField();
        txtTipSobe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        btnKreirajRezervaciju = new javax.swing.JButton();
        btnIzaberiKlijenta = new javax.swing.JButton();
        lblBrojrezervacije = new javax.swing.JLabel();
        txtBrojRezervacije = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlKlijenta.setLayout(new java.awt.GridLayout(1, 1));

        btnIzaberiPonudu.setText("Izaberi ponudu");
        btnIzaberiPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiPonuduActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ponuda"));

        jLabel1.setText("Drzava:");

        txtDrzava.setEditable(false);

        jLabel2.setText("Grad:");

        txtGrad.setEditable(false);

        txtDatumOd.setEditable(false);

        jLabel4.setText("Datum od:");

        jLabel5.setText("Datum do:");

        txtDatumDo.setEditable(false);

        jLabel6.setText("Hotel:");

        txtHotel.setEditable(false);

        txtTipSobe.setEditable(false);

        jLabel7.setText("Tip sobe:");

        jLabel8.setText("Cena:");

        txtCena.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)
                        .addComponent(txtDatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addComponent(txtDatumDo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75)
                        .addComponent(txtGrad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(txtDrzava))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(73, 73, 73)
                        .addComponent(txtHotel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(txtTipSobe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(73, 73, 73)
                        .addComponent(txtCena)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTipSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel3))
        );

        btnKreirajRezervaciju.setText("Kreiraj rezervaciju");
        btnKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajRezervacijuActionPerformed(evt);
            }
        });

        btnIzaberiKlijenta.setText("Izaberi klijenta");
        btnIzaberiKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiKlijentaActionPerformed(evt);
            }
        });

        lblBrojrezervacije.setText("Broj rezervacije:");

        txtBrojRezervacije.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlKlijenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBrojrezervacije)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrojRezervacije))
                    .addComponent(btnIzaberiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnIzaberiPonudu, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreirajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrojrezervacije, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBrojRezervacije, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIzaberiPonudu)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIzaberiKlijenta)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnKreirajRezervaciju)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiKlijentaActionPerformed
        FrmPretragaKlijenata frm = new FrmPretragaKlijenata(this, false,FrmMode.PRETRAGA);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_btnIzaberiKlijentaActionPerformed

    private void btnIzaberiPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiPonuduActionPerformed
        FrmPretragaPonuda frm = new FrmPretragaPonuda(this, false, FrmMode.PRIKAZ);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_btnIzaberiPonuduActionPerformed

    private void btnKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajRezervacijuActionPerformed
        try {
            if(k==null || sp==null) {
                JOptionPane.showMessageDialog(this, "Izbarite klijenta i ponudu", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Rezervacija r = new Rezervacija(0, k, sp, new Date());
            if (sp.getKapacitet() > 0) {
                sp.setKapacitet(sp.getKapacitet() - 1);
                Kontroler.getInstanca().kreirajRezervaciju(r);
                JOptionPane.showMessageDialog(this, "Uspesno kreirana rezervacija");
                isprazniPoljaForme();
            } else {
                JOptionPane.showMessageDialog(this, "Popunjen kapacitet za ovu ponudu", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKreirajRezervacijuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiKlijenta;
    private javax.swing.JButton btnIzaberiPonudu;
    private javax.swing.JButton btnKreirajRezervaciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBrojrezervacije;
    private javax.swing.JPanel pnlKlijenta;
    private javax.swing.JTextField txtBrojRezervacije;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtDatumDo;
    private javax.swing.JTextField txtDatumOd;
    private javax.swing.JTextField txtDrzava;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtHotel;
    private javax.swing.JTextField txtTipSobe;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        pnlKlijent = new PnlKlijent(FrmMode.PRIKAZ);
        pnlKlijenta.add(pnlKlijent);
        pnlKlijent.setEnabled(false);
        jPanel1.setEnabled(false);
        
        switch(mode) {
            case UNOS:
                lblBrojrezervacije.setVisible(false);
                txtBrojRezervacije.setVisible(false);
                break;
            case PRIKAZ:
                btnIzaberiKlijenta.setVisible(false);
                btnIzaberiPonudu.setVisible(false);
                btnKreirajRezervaciju.setVisible(false);
                
                Rezervacija r = (Rezervacija) Sesija.getInstanca().getMapa().get("Rezervacija");
                txtBrojRezervacije.setText(r.getBrojRezervacije() + "");
                ubaciKlijenta(r.getKlijent());
                ubaciPonudu(r.getStavkaPonude());
                break;
        }
        
    }
    
    public void ubaciKlijenta(Klijent k) {
        this.k = k;
        pnlKlijent.setTxtIme(k.getIme());
        pnlKlijent.setTxtJMBG(k.getJmbg());
        pnlKlijent.setTxtPrezime(k.getPrezime());
        pnlKlijent.setTxtBrojPasosa(k.getBrojPasosa());
        pnlKlijent.setTxtTelefon(k.getTelefon());
        pnlKlijent.setTxtEmail(k.getEmail());
    }
    
    public void ubaciPonudu(StavkaPonude sp) {
        this.sp = sp;
        txtDrzava.setText(sp.getPonuda().getGrad().getDrzava().getNaziv());
        txtGrad.setText(sp.getPonuda().getGrad().toString());
        SimpleDateFormat sf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumOd.setText(sf.format(sp.getPonuda().getDatumOd()));
        txtDatumDo.setText(sf.format(sp.getPonuda().getDatumDo()));
        txtHotel.setText(sp.getPonuda().getHotel().toString());
        txtTipSobe.setText(sp.getTipSobe().toString());
        txtCena.setText(sp.getCena() + "");
    }
    
    private void isprazniPoljaForme() {
        pnlKlijent.isprazniPoljaForma();
        txtCena.setText("");
        txtDatumDo.setText("");
        txtDatumOd.setText("");
        txtDrzava.setText("");
        txtGrad.setText("");
        txtHotel.setText("");
        txtTipSobe.setText("");
    }
    
}
