/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.paneli;

import domen.Klijent;
import forme.dijalozi.FrmPretragaKlijenata;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
import kotroler.Kontroler;
import sesija.Sesija;

/**
 *
 * @author Jovana Mitrovic
 */
public class PnlKlijent extends javax.swing.JPanel {

    FrmMode mode;

    /**
     * Creates new form PnlUnosKlijenta
     */
    public PnlKlijent(FrmMode mode) {
        this.mode = mode;
        initComponents();
        srediFormu();
    }

    public void setTxtBrojPasosa(String txtBrojPasosa) {
        this.txtBrojPasosa.setText(txtBrojPasosa);
    }

    public void setTxtEmail(String txtEmail) {
        this.txtEmail.setText(txtEmail);
    }

    public void setTxtIme(String txtIme) {
        this.txtIme.setText(txtIme);
    }

    public void setTxtJMBG(String txtJMBG) {
        this.txtJMBG.setText(txtJMBG);
    }

    public void setTxtPrezime(String txtPrezime) {
        this.txtPrezime.setText(txtPrezime);
    }

    public void setTxtTelefon(String txtTelefon) {
        this.txtTelefon.setText(txtTelefon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBrojPasosa = new javax.swing.JTextField();
        btnUnesiKlijenta = new javax.swing.JButton();
        btnIzmeniKlijenta = new javax.swing.JButton();

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("JMBG:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("E-mail:");

        jLabel5.setText("Telefon:");

        jLabel6.setText("Broj pasosa:");

        btnUnesiKlijenta.setText("Unesi klijenta");
        btnUnesiKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiKlijentaActionPerformed(evt);
            }
        });

        btnIzmeniKlijenta.setText("Izmeni klijenta");
        btnIzmeniKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKlijentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(txtBrojPasosa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUnesiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzmeniKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBrojPasosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUnesiKlijenta)
                .addGap(18, 18, 18)
                .addComponent(btnIzmeniKlijenta)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiKlijentaActionPerformed
        String jmbg = txtJMBG.getText().trim();
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        String telefon = txtTelefon.getText().trim();
        String brojPasosa = txtBrojPasosa.getText().trim();

        if (validacija()) {
            try {
                Klijent k = new Klijent(0, jmbg, ime, prezime, email, telefon, brojPasosa);
                Kontroler.getInstanca().unesiKlijenta(k);
                JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali klijenta");
                isprazniPoljaForma();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUnesiKlijentaActionPerformed

    private void btnIzmeniKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKlijentaActionPerformed
        Klijent k = (Klijent) Sesija.getInstanca().getMapa().get("Klijent");
        String jmbg = txtJMBG.getText().trim();
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        String telefon = txtTelefon.getText().trim();
        String brojPasosa = txtBrojPasosa.getText().trim();

        if (validacija()) {
            try {
                k.setJmbg(jmbg);
                k.setIme(ime);
                k.setPrezime(prezime);
                k.setEmail(email);
                k.setTelefon(telefon);
                k.setBrojPasosa(brojPasosa);
                Kontroler.getInstanca().izmeniKlijenta(k);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili klijenta");
                FrmPretragaKlijenata frm = (FrmPretragaKlijenata) SwingUtilities.getWindowAncestor(this).getParent();
                frm.popuniTabelu();
                SwingUtilities.getWindowAncestor(this).dispose();
            } catch (Exception ex) {
                Logger.getLogger(PnlKlijent.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnIzmeniKlijentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniKlijenta;
    private javax.swing.JButton btnUnesiKlijenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtBrojPasosa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        switch (mode) {
            case UNOS:
                btnIzmeniKlijenta.setVisible(false);
                panel.setBorder(new TitledBorder("Unesi klijenta"));
                break;
            case PRIKAZ:
                panel.setEnabled(false);
                btnUnesiKlijenta.setVisible(false);
                btnIzmeniKlijenta.setVisible(false);
                panel.setBorder(new TitledBorder("Klijent"));
                txtBrojPasosa.setEditable(false);
                txtEmail.setEditable(false);
                txtIme.setEditable(false);
                txtJMBG.setEditable(false);
                txtPrezime.setEditable(false);
                txtTelefon.setEditable(false);
                break;
            case IZMENA:
                Klijent k = (Klijent) Sesija.getInstanca().getMapa().get("Klijent");
                panel.setBorder(new TitledBorder("Izmena klijenta"));
                txtBrojPasosa.setText(k.getBrojPasosa());
                txtEmail.setText(k.getEmail());
                txtIme.setText(k.getIme());
                txtJMBG.setText(k.getJmbg());
                txtPrezime.setText(k.getPrezime());
                txtTelefon.setText(k.getTelefon());
                btnUnesiKlijenta.setVisible(false);
                break;

        }
    }

    public void isprazniPoljaForma() {
        txtBrojPasosa.setText("");
        txtEmail.setText("");
        txtIme.setText("");
        txtJMBG.setText("");
        txtPrezime.setText("");
        txtTelefon.setText("");
    }

    public boolean validacija() {
        String jmbg = txtJMBG.getText().trim();
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        String telefon = txtTelefon.getText().trim();
        String brojPasosa = txtBrojPasosa.getText().trim();

        if (jmbg.isEmpty() || ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || telefon.isEmpty() || brojPasosa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna!", "Greska", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (jmbg.length() != 13) {
            JOptionPane.showMessageDialog(this, "JMBG mora da sadrzi 13 cifara!", "Greska", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "E-mail mora da sadrzi '@'!", "Greska", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }


}
